# Generated by Django 5.0.10 on 2025-01-15 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('firma', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('passwort', models.CharField(max_length=255)),
                ('kommentar', models.CharField(blank=True, max_length=255, null=True)),
                ('erstelldatum', models.DateTimeField()),
            ],
            options={
                'db_table': 'office_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RMATicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketnummer', models.CharField(max_length=100, unique=True)),
                ('firma', models.CharField(blank=True, max_length=255, null=True)),
                ('modell', models.CharField(blank=True, max_length=255, null=True)),
                ('seriennummer', models.CharField(blank=True, max_length=255, null=True)),
                ('fehler', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('abgeschlossen', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('general', 'General'), ('computacenter', 'Computacenter')], max_length=50)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('firma', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('startdatum', models.DateField()),
                ('ablaufdatum', models.DateField()),
                ('seriennummer', models.CharField(max_length=100, unique=True)),
                ('typ', models.CharField(choices=[('garantie', 'Garantie'), ('lizenz', 'Lizenz')], default='garantie', max_length=20)),
                ('kommentar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lizenz_schluessel', models.CharField(max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GDataAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now_add=True)),
                ('initialen', models.CharField(max_length=10)),
                ('firma', models.CharField(max_length=255)),
                ('nachname', models.CharField(max_length=255)),
                ('vorname', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=20)),
                ('ort', models.CharField(max_length=100)),
                ('benutzername', models.CharField(max_length=150, unique=True)),
                ('passwort', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('auftrag_typ', models.CharField(choices=[('1_jahr', '1 Jahr'), ('2_jahre', '2 Jahre'), ('3_jahre', '3 Jahre')], default='1_jahr', max_length=20)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('lizenz_schluessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pcrmgmtAPP.licensekey')),
            ],
            options={
                'db_table': 'gdata_accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('modern', 'Modern'), ('soft-blue', 'Soft Blue'), ('soft-green', 'Soft Green'), ('vintage', 'Vintage'), ('high-contrast', 'High Contrast'), ('elegant', 'Elegant'), ('sunset', 'Sunset'), ('neon', 'Neon'), ('pastel', 'Pastel')], default='dark', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
