# Generated by Django 5.0.10 on 2025-01-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('firma', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('passwort', models.CharField(max_length=255)),
                ('kommentar', models.CharField(blank=True, max_length=255, null=True)),
                ('erstelldatum', models.DateTimeField()),
            ],
            options={
                'db_table': 'office_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('light-dark', 'Light-Dark'), ('metallic-blue', 'Metallic Blue'), ('metallic-green', 'Metallic Green'), ('carbon', 'Carbon')], default='light', max_length=20)),
                ('script_interval', models.PositiveIntegerField(default=60)),
                ('timespan_days', models.PositiveIntegerField(default=30)),
                ('script_running', models.BooleanField(default=False)),
            ],
        ),
    ]
