# Generated by Django 5.0.10 on 2025-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrmgmtAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='script_interval',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
