# Generated by Django 5.0.10 on 2025-01-05 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrmgmtAPP', '0002_alter_settings_script_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='script_interval',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='script_running',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='timespan_days',
        ),
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('modern', 'Modern'), ('soft-blue', 'Soft Blue'), ('soft-green', 'Soft Green')], default='light', max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('modern', 'Modern'), ('soft-blue', 'Soft Blue'), ('soft-green', 'Soft Green')], default='light', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
