# Generated by Django 5.0.10 on 2025-01-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrmgmtAPP', '0003_remove_settings_script_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('modern', 'Modern'), ('soft-blue', 'Soft Blue'), ('soft-green', 'Soft Green'), ('vintage', 'Vintage'), ('high-contrast', 'High Contrast'), ('elegant', 'Elegant')], default='dark', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('modern', 'Modern'), ('soft-blue', 'Soft Blue'), ('soft-green', 'Soft Green'), ('vintage', 'Vintage'), ('high-contrast', 'High Contrast'), ('elegant', 'Elegant')], default='dark', max_length=20),
        ),
    ]
